services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: quotes
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5433:5432 # Different port for the second instance
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
